name: build

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK
      id: setup-jdk
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: build
      run: ./gradlew build
    - name: archive vgo test results
      uses: actions/upload-artifact@v1
      with:
        name: vgo_test_results
        path: vgo/build/reports/tests/test/
    - name: archive vgo core test results
      uses: actions/upload-artifact@v1
      with:
        name: vgo_core_test_results
        path: vgo-core/build/reports/tests/test/
    - name: release binary
      run: ./gradlew binary
    - name: archive vgo
      uses: actions/upload-artifact@v1
      with:
        name: vgo
        path: vgo/build/libs/vgo
